org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=greedycanteen
modName=Mekanism: Greedy Canteen
modLicense=MIT
modGroupId=net.meatwo310.greedycanteen
modAuthors=Meatwo310
modDescription=Modifies Mekanism's Canteen and Nutritional Injection Unit to feed players until their saturation reaches a configurable target.
modDisplayUrl=https://github.com/Meatwo310/mekanism-greedy-canteen
modIssueTrackerUrl=https://github.com/Meatwo310/mekanism-greedy-canteen/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=net.meatwo310.greedycanteen.ModMain
modFabricClientEntrypoint=net.meatwo310.greedycanteen.client.ModClient
